### ISSUE TITLE
earth nav data not found due to being case sensitive 

### ISSUE THREAD

**Issue by ale-novo** [dyoung522/ovt#11]
OS: Linux
Ortho4XP 1.3 creates directories called 'Earth nav data' with capital 'E'
otv looks for 'earth nav data' lowercase, failing to find the directory on Linux that is a case sensitive OS.

Propose solution: Ignore the case for any combination of capitals that is legal with x-plane.
thanks for the work.

**Comment by dyoung522** [comment]
Thank you for the fix @jonaseberle !

**Comment by jonaseberle** [comment]
Thank you for this tool!
